name: Run Tests
on: push

jobs:
  run-chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        npm i
        npm run cy:run:${{ matrix.browser }}
